name: Build and Deploy Go app to Azure Web App

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Go
           uses: actions/setup-go@v4
           with:
              go-version: "1.22.3"

         - name: Build
           run: |
              go build -o myapp .

         - name: Deploy to Azure Web App
           uses: azure/webapps-deploy@v2
           with:
              app-name: "<todo-app-backend>"
              slot-name: "production"
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: .
