name: Build and Deploy Go app to Azure Web App

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Go
           uses: actions/setup-go@v4
           with:
              go-version: "latest"

         - name: Build
           run: go build -o myapp .

         - name: Archive application files
           run: zip -r myapp.zip .

         - name: Deploy to Azure Web App
           uses: azure/webapps-deploy@v2
           with:
              app-name: "your-app-name" # Replace with your Azure Web App name
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: "./myapp.zip"
